###########################################################################
# UPSTREAMS HTTPS (Porta 443)
###########################################################################

upstream deny_backend {
    server 127.0.0.1:9;
}


upstream sentry {
    server 192.168.1.49:443;
    # Configurações opcionais:
    # server 192.168.1.204:443 backup;  # Servidor de backup
    # keepalive 32;                      # Conexões persistentes
}

upstream grafana {
    server 192.168.1.104:443;
}

upstream allDefault {
    server 192.168.1.116:443;
}
upstream otlp {
    server 192.168.1.223:4317;
}

upstream ollama {
    server 192.168.1.233:443;
}

upstream openreplay {
    server 192.168.1.70:443;
}

upstream prometheus {
    server 192.168.1.104:9091;
}
upstream monitor {
    server 192.168.1.103:443;
}
upstream proxy {
    server 192.168.1.103:8443;
}
upstream clawd {
    server 192.168.1.54:443;
}
upstream supabase {
    server 192.168.1.37:4432;
}
upstream coolify {
    server 192.168.1.35:8443;
}
upstream coolifydef {
    server 192.168.1.35:443;
}
# Mapeamento HTTPS (443) - baseado em SNI
map $ssl_preread_server_name $lk_backend_name_https {
    # Formato: dominio.com backend_name;
    sentry.sittax.com.br      sentry;
    grafana.sittax.com.br     grafana;
    otlp.sittax.com.br        otlp;
    ollama.sittax.com.br      ollama;
    openreplay.sittax.com.br  openreplay;
    prometheus.sittax.com.br  prometheus;
    monitor.sittax.com.br     monitor;
    monitorrabbit.sittax.com.br     monitor;
    #clawd.sittax.com.br	      clawd;

    supabase.sittax.com.br    supabase;
    supabase.sittax.com       supabase;
    coolify.sittax.com.br     coolify;
    coolify.sittax.com        coolify;
    proxy.sittax.com.br       proxy;

    sittax.com.br             monitor;
    sittax.com                monitor;

    # Wildcards (se necessário no futuro)
    # *.sentry.sittax.com.br  sentry;

    appwrite.sittax.com.br    coolifydef;
    # Default
    default                   allDefault;
}

###########################################################################
# BLOQUEIO DE IPs ESPECÍFICOS PARA O DOMÍNIO prometheus.sittax.com.br
###########################################################################

# Define quem pode conectar (1 = permitido, 0 = bloqueado)
geo $allowed_ip {
    default 1;  # tudo bloqueado por padrão

    177.223.44.35      1;   # Local Server Public IP

    179.253.141.253    1;   # Devops


    # Oracle Servers
    129.151.34.229     1;   # DBServer
    168.75.93.95       1;   # Telemetry Collector
    137.131.155.44     1;   # AppServerProd02
    168.138.153.188    1;   # ServiceServerProd
    144.22.229.35      1;   # AppServerProd

    # Redes locais
    192.168.1.0/24     1;   # IP local específico
    10.0.0.0/16        1;   # Faixa de VPN/IPs
    172.20.0.0/16      1;   # Rede Docker
}

# Combina domínio (SNI) e IP permitido
map "$ssl_preread_server_name:$allowed_ip" $backend_name_https {

    "prometheus.sittax.com.br:0"           deny_backend;                  # bloqueado
    "monitor.sittax.com.br:0"              deny_backend;
    default                                $lk_backend_name_https;           # todos os outros domínios permitidos

}
