###########################################################################
# UPSTREAM & ROTEAMENTO HÍBRIDO - PORTA 80 (STREAM)
# Permite bypass do roteador HTTP (8080) para serviços específicos
###########################################################################

# Upstream para o roteador HTTP interno (Fallback para tráfego comum)
upstream http_router {
    server 127.0.0.1:8080;
}

# Upstream direto para o proxy (Bypass do overhead do 8080)
upstream proxy_direct_8888 {
    server 192.168.1.103:8888;
}

# Mapeamento baseado em SNI para decidir o destino na porta 80
map $ssl_preread_server_name $backend_name_80 {
    proxy.sittax.com.br       proxy_direct_8888;
    
    # Adicione abaixo outros domínios que devem permanecer no Stream
    # dominio.com.br          outro_upstream;

    default                   http_router;
}
